# Generated by Django 3.1.7 on 2021-04-01 16:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание категории')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Изображение для категории')),
                ('sort_weight', models.PositiveIntegerField(default=0, verbose_name='Вес для сортировки')),
                ('seo_keywords', models.CharField(blank=True, max_length=100, verbose_name='Ключевые слова для SEO')),
                ('seo_description', models.CharField(blank=True, max_length=100, verbose_name='Описание для SEO')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
                'ordering': ('-sort_weight', 'id'),
            },
        ),
    ]
