# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 13:55
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20170918_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание категории'),
        ),
    ]
