# Generated by Django 3.1.7 on 2021-04-01 16:15

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Название товара')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('article', models.CharField(blank=True, max_length=50, verbose_name='Артикул')),
                ('short_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Краткое описание')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Полное описание')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Главная картинка')),
                ('weight', models.IntegerField(blank=True, default=0, verbose_name='Вес товара')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен для заказа')),
                ('sort_weight', models.PositiveIntegerField(default=0, verbose_name='Вес для сортировки')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления товара')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category', verbose_name='Категория')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Товар добавил')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('-sort_weight', '-id'),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProductMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(default='', max_length=10, verbose_name='Краткое наименование')),
                ('full', models.CharField(default='', max_length=50, verbose_name='Полное наименование')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Описание цены')),
                ('package_quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productmeasure', verbose_name='Единица измерения')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='shop.product', verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.CreateModel(
            name='ProductAdditionalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Дополнительная картинка товара')),
                ('alt', models.CharField(blank=True, max_length=100, verbose_name='Alt текст изображения')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_images', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товара',
            },
        ),
    ]
