# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20170915_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Описание цены')),
                ('package_quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество в упаковке')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('sort_weight', 'id'), 'verbose_name': 'Категория товара', 'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('sort_weight', 'id'), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='category',
            name='sort_weight',
            field=models.PositiveIntegerField(default=0, verbose_name='Вес для сортировки'),
        ),
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, max_length=50, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Краткое описание товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='sort_weight',
            field=models.PositiveIntegerField(default=0, verbose_name='Вес для сортировки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, default=0, verbose_name='Вес товара'),
        ),
        migrations.AlterField(
            model_name='productadditionalimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_images', to='shop.Product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='shop.Product', verbose_name='Цена'),
        ),
    ]
