# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20170915_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('sort_weight', '-id'), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='productprice',
            name='measure',
            field=models.CharField(default=1, max_length=50, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='productadditionalimage',
            name='alt',
            field=models.CharField(blank=True, max_length=100, verbose_name='Alt текст изображения'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='package_quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
