# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20170915_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmeasure',
            name='name',
        ),
        migrations.AddField(
            model_name='productmeasure',
            name='full',
            field=models.CharField(default='', max_length=50, verbose_name='Полное наименование'),
        ),
        migrations.AddField(
            model_name='productmeasure',
            name='short',
            field=models.CharField(default='', max_length=10, verbose_name='Краткое наименование'),
        ),
    ]
